### ISSUE TITLE
HandbrakeCLI: "MP4ERROR: File size exceeded 4 GB; output unplayable."

### ISSUE THREAD

**Issue by marcoarment** [donmelton/video-transcoding-scripts#18]
Just ran the latest `transcode-video.sh` on a Blu-ray movie rip (*Snatch*, 102 min) with settings `--big --no-surround --burn 12 --crop 20:20:0:0`, and the transcode ended with the log below. The output MP4 is 5.74 GB and neither QuickTime nor VLC are willing to play it.

Is enabling "Large file size" my bug or yours?

```
x264 [info]: ref P L0: 58.5% 12.3% 18.7% 10.0%  0.5%
x264 [info]: ref B L0: 81.8% 17.0%  1.3%
x264 [info]: ref B L1: 97.6%  2.4%
x264 [info]: SSIM Mean Y:0.9723527 (15.583db)
x264 [info]: PSNR Mean Y:44.493 U:50.391 V:52.480 Avg:45.647 Global:44.848 kb/s:7315.16
[00:33:13] dca-decoder done: 0 frames, 0 decoder errors, 0 drops
Muxing: this may take awhile...MP4ERROR: File size exceeded 4 GB; output unplayable. Enable "Large file size" to fix it.
MP4ERROR: (m_size <= (uint64_t)0xFFFFFFFF): assert failure
[00:33:13] mux: track 0, 147232 frames, 5615050889 bytes, 7315.03 kbps, fifo 1024
[00:33:13] mux: track 1, 287851 frames, 125712951 bytes, 163.77 kbps, fifo 2048
[00:33:15] libhb: work result = 0

Encode done!
HandBrake has exited.


real	97m38.779s
user	743m5.884s
sys	5m48.836s
```

**Comment by marcoarment** [comment]
Never mind, my bug. Old version of HandBrakeCLI was lingering in PATH.

**Comment by donmelton** [comment]
What version of `HandBrakeCLI` are you using? This often happens with versions prior to `0.10.0`, the current stable release.

I actually removed `--large-file` support in an update on December 30, 2014 because the HandBrake developers removed the option instead of just deprecating it. Really stupid move.

You can check your version number on OS X with this command:

    strings ~/bin/HandBrakeCLI | grep ^HandBrake | sed -n 1p

**Comment by donmelton** [comment]
Aaaaand... nevermind my comment which was posted 10 seconds after you closed this. :)
