### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by jhawk28** [donmelton/video-transcoding-scripts#19]
It would be nice to pass in the aspect ratio for when handbrake doesn't properly set it. I have had a few videos that take a 720x480 output 640x480.

**Comment by donmelton** [comment]
Sorry I took so long to reply.

Adding this will make the code handling the automatic behavior much more complicated. :) But I'm willing to consider it.

I assume you want to specify the aspect ratio as a boundary then? That is, with `--width` and `--height` options?

**Comment by jhawk28** [comment]
Yes, --width and --height

**Comment by donmelton** [comment]
OK, I think I can do this just by changing the the pixel aspect ratio with HandBrake's `--custom-anamorphic` option. That way you can specify only `--width`, only `--height`, or both.

I'll put this on my feature list for a release I'm planning on in the next two weeks. And I'll leave this issue open until the feature goes in or I hit a wall with the implementation.

**Comment by donmelton** [comment]
I finally got around to implementing it tonight. Seems to work fine but I'll wait to release it after I test it and the other new features more. It'll probably be out in a few days.

**Comment by jhawk28** [comment]
thanks much

**Comment by donmelton** [comment]
While these new options seem to work for some folks, I think an aspect ratio-specific option might be better. So I'm planning on adding that to the rewrite of the scripts that I'm working on now. Since that rewrite will be a Ruby-based Gem, it's unlikely I'll back-port it to my Bash-based shell scripts.

So I'm closing this now.
