### ISSUE TITLE
"encx264: unparsed options:"

### ISSUE THREAD

**Issue by ConradAndersen** [donmelton/video-transcoding-scripts#26]
Hi

First of all thanks for these great scripts!

I'm not sure if this is an actual issue, but whenever i use transcode-video.sh i'm getting the following line:

"encx264: unparsed options: vbv-maxrate=3000:vbv-bufsize=1500:crf-max=25"

If i just read this line, it seems like those parameters are not used for converting?

CLI program versions:

HandbrakeCLI: "HandBrake 0.10.1 (2015030800) - Darwin x86_64"

mkvpropedit: "mkvpropedit v7.7.0 ('Six Voices') 64bit built on Mar  1 2015 18:00:50"

MPlayer: "MPlayer 1.1-4.2.1 (C) 2000-2012 MPlayer Team"

mkvmerge: "mkvmerge v7.7.0 ('Six Voices') 64bit built on Mar  1 2015 18:00:50"

ffmpeg: "ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfaac --enable-libfdk-aac --enable-libx265 --enable-nonfree --enable-vda"

mp4track: "mp4track - MP4v2 2.0.0"

**Comment by donmelton** [comment]
Conrad,

You are very welcome! Glad you like them. And it seems you're reading your console output and log files. Excellent! Everyone should do that.

But, not to worry. That misleading "encx264: unparsed options" message is simply telling you that HandBrake itself didn't parse those encoder options and instead passed them straight through to x264, the transcoding library within HandBrake. So, they're definitely being used.

You can verify this yourself with the MediaInfo tool available [here](http://mediaarea.net/en/MediaInfo>) or via `brew install media-info` from Homebrew.

When you inspect a transcoded file like this:

```
mediainfo "/path/to/Movie.mkv"
```

... MediaInfo will show you all the options used by x264.

This isn't the first time someone has asked me about the "encx264: unparsed options" line. I should really add that to the README. :)

Thanks for your question!
