### ISSUE TITLE
Question about warnings/errors at beginning of script execution (transcode-video.sh)

### ISSUE THREAD

**Issue by kford** [donmelton/video-transcoding-scripts#30]
Hi Don,

On all my transcodes, I get the same warnings/errors as you see in [this issue](https://github.com/donmelton/video-transcoding-scripts/issues/21).  Maybe your script tests something and uses the output to switch behavior, but I thought I'd check with you to make sure I'm not doing something wrong.

Namely these:
* stat: cannot read file system information for ‘%z’: No such file or directory
* Inodes: Total: 1000       Free: 1000 * 8) / ((duration_array[0] * 60 * 60) + (duration_array[1] * 60) + duration_array[2]): missing `)' (error token is ": "NYSM/Now_You_See_Me_t00.mkv"

**Comment by donmelton** [comment]
@kford I'm now deprecating these scripts and advising people to use my Ruby-based tools at:

<https://github.com/donmelton/video_transcoding>

... instead.

I'm sorry I took so long to reply. Can you try the new tools and see if you have the same problem?
