### ISSUE TITLE
transcode-video.sh: can't determine HandBrakeCLI version

### ISSUE THREAD

**Issue by jpontius** [donmelton/video-transcoding-scripts#31]
I'm having the same problem as @69dragons and @agrajag9.   I get the error "transcode-video.sh: can't determine HandBrakeCLI version" and just dumps me back to the prompt. 

I'm running Ubuntu Trusty with ````HandBrake 20151003171838-7323a7d-master````.

````
HandBrakeCLI --preset-list 2>&1 | head -n1
[11:51:36] hb_init: starting libhb thread
````

**Comment by donmelton** [comment]
@jpontius Are you having this same problem with the new Ruby-based tools which replace `transcode-video.sh`? See: https://github.com/donmelton/video_transcoding

**Comment by donmelton** [comment]
@jpontius I'm closing this issue since I've officially deprecated these scripts in favor of the new Ruby-based tools.
