### ISSUE TITLE
Script doesn't pull English Audio

### ISSUE THREAD

**Issue by racinrandall** [donmelton/video-transcoding-scripts#33]
Some of the files I need to process contain audio tracks other than English and English isn't always the first or even in AC3.  I'm just starting to comb through your script and try to understand it.  I would like for it to always pull the English Audio and passthrough DTS if it is available.  Not sure if the script does it or not because I haven't tested it on a file that has it, but what about burned in foreign audio scan?

**Comment by donmelton** [comment]
@racinrandall I'm officially deprecating these Bash-based scripts in favor of my Ruby-based tools at:

<https://github.com/donmelton/video_transcoding>

I think you'll find the new tools will do what you want. Sorry that I took so long to comment here.
