### ISSUE TITLE
Since this older project is deprecated should it be removed?

### ISSUE THREAD

**Issue by edrozenberg** [donmelton/video-transcoding-scripts#34]
Since the current project is https://github.com/donmelton/video_transcoding, wondering if this older project "video-transcoding-scripts" should be deleted so people don't come to it by accident? Also this older project shows up higher in Google search than the active project.

**Comment by shuckster** [comment]
I didn't know this wasn't the latest version of the project until now, so +1 from me. :D

**Comment by gingerbeardman** [comment]
+1

**Comment by donmelton** [comment]
@edrozenberg @shuckster and @gingerbeardman Good points. It's a problem. I'll probably first take @JMoVS 's patch here https://github.com/donmelton/video-transcoding-scripts/pull/28 to update the README first.

**Comment by donmelton** [comment]
OK, I've updated the README with a warning, deprecation notice and link to the new project. But I don't plan on removing it. So I'll close this now.

**Comment by gingerbeardman** [comment]
Works for me, thanks @donmelton
