### ISSUE TITLE
Merge 2 mkv:s?

### ISSUE THREAD

**Issue by torstensson** [donmelton/video-transcoding-scripts#6]
Hi Don! First of all - Thanks a bunch for your awesome work! I truly love it, and am very grateful for it. You should see the stack of bluray's I have, just waiting for some sweet TLC from my new BFF transcode-video.sh ;)

Now, to my question/issue; I have the extended version of Lord of the Rings which I intend to rip+transcode for future safekeeping. However, those movies are so humongous, each one is on two BD discs. Is there any sweet command I have overlooked to merge those files during transcoding, or any other readily available parlour trick to achieve the illusion of one giant-ass film (x3)? I see from your requirements page (https://github.com/donmelton/video-transcoding-scripts#requirements) you mention mkvmerge as a required tool, but I can't really understand how it is supposed be used. I.e. is there any built-in support for merge, not mentioned in --fullhelp, built in to your scripts, or is Google my friend on how manage mkvmerge before using transcode-video.sh?

In hope that this question reaches and intrigues you - All the best!
-Per

EDIT: I seem to have found what I am looking for - https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html
I will test this as soon as I have ripped two discs, and report my findings

**Comment by yongcomeon** [comment]
You may also try iDealshare VideoGo to join MKV files into one on Mac or Windows at http://www.idealshare.net/video-joiner-for-mac-windows.html

It also helps to:
Join video files of any format like merge MP4, AVI, MPEG, MPG, VOB, MOV, RM, RMVB, 3GP, ASF, WMV, WTV, DVR, DivX, Xvid, M4V, MKV, FLV, F4V, SWF, WebM, OGV, Apple ProRes, AVCHD, MTS, M2TS, M2T, MXF, MVI, DAT, MOD, TOD, MPV, OGM and etc

Merge audio files like join MP3, WAV, WMA, M4A, FLAC, M4B, AAC, AC3, APE, AIFF, Apple Lossless ALAC, VOC, QCP, AMR, AWB, DTS, AU, RA, OGG and more.
